name: Pull Request Build and Test
on:
  pull_request:

jobs:
  call-ci-workflow:
    uses: emerging-eco/ixo-github-actions/.github/workflows/node-ci-pr.yml@main
    with:
      package_manager: yarn
      node_version: "20"