name: Build and Release 
on:
  push:
    branches:
      - prod
      - dev
      - stage
jobs:
  build-and-release:
    uses: emerging-eco/ixo-github-actions/.github/workflows/node-ci-build.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package_manager: yarn
    secrets: inherit
